import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

const migration = readFile(new URL('../supabase/migrations/20261007104000_0081_idempotent_chat_messages.sql', import.meta.url), 'utf8');
const alice = '10000000-0000-0000-0000-000000000001';
const bob = '10000000-0000-0000-0000-000000000002';
const nonce = '20000000-0000-0000-0000-000000000001';

test('message retries reuse one stored row and reject conflicting payloads', async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      create schema auth; create role anon; create role authenticated;
      create function auth.uid() returns uuid language sql stable as
        $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
      create table public.profiles(id uuid primary key, name text, deactivated_at timestamptz);
      create table public.sessions(id bigint primary key, mentor_id uuid, mentee_id uuid);
      create table public.group_members(group_id bigint, user_id uuid);
      create table public.session_messages(id bigint generated by default as identity primary key,
        session_id bigint, sender_id uuid, kind text, body text, created_at timestamptz default now());
      create table public.group_messages(id bigint generated by default as identity primary key,
        group_id bigint, sender_id uuid, body text, created_at timestamptz default now());
      create function public.is_active_user() returns boolean language sql stable as $$
        select exists(select 1 from profiles where id = auth.uid() and deactivated_at is null) $$;
      create function public.send_session_message(bigint, text) returns jsonb language sql as $$ select '{}'::jsonb $$;
      create function public.send_group_message(bigint, text) returns jsonb language sql as $$ select '{}'::jsonb $$;
      insert into profiles values ('${alice}', 'Alice', null), ('${bob}', 'Bob', null);
      insert into sessions values (1, '${alice}', '${bob}');
      insert into group_members values (1, '${alice}');
    `);
    await db.exec(await migration);
    await db.query("select set_config('request.jwt.claim.sub', $1, false)", [alice]);

    for (const [send, table, read] of [
      ['select public.send_session_message(1, $1, $2::uuid) as message', 'session_messages', 'select public.my_session_messages(1) as page'],
      ['select public.send_group_message(1, $1, $2::uuid) as message', 'group_messages', 'select public.my_group_messages(1) as page'],
    ]) {
      const first = (await db.query(send, ['Hello', nonce])).rows[0].message;
      const retry = (await db.query(send, ['Hello', nonce])).rows[0].message;
      assert.equal(retry.id, first.id);
      assert.equal((await db.query(`select count(*)::integer as n from ${table}`)).rows[0].n, 1);
      assert.equal((await db.query(read)).rows[0].page.messages[0].client_id, nonce);
      await assert.rejects(db.query(send, ['Different', nonce]), /message_id_conflict/);
    }

    await db.query("update profiles set deactivated_at = now() where id = $1", [alice]);
    await assert.rejects(db.query('select public.send_session_message(1, $1, $2::uuid)', ['Hello', nonce]), /account_deactivated/);
    await assert.rejects(db.query('select public.my_session_messages(1)'), /account_deactivated/);
  } finally {
    await db.close();
  }
});
