-- Persist mentoring conversations and enforce user-owned acceptance capacity.

alter table public.profiles
  add column if not exists linkedin_url text,
  add column if not exists linkedin_headline text;

alter table public.profiles drop constraint if exists profiles_linkedin_url_length;
alter table public.profiles add constraint profiles_linkedin_url_length
  check (linkedin_url is null or char_length(linkedin_url) <= 500);

grant update (weekly_meeting_limit, monthly_meeting_limit, linkedin_url, linkedin_headline)
  on public.profiles to authenticated;

create or replace function public.peer_linkedin(p_user_id uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare caller uuid := auth.uid(); caller_org uuid; target public.profiles;
begin
  if caller is null then raise exception 'auth_required'; end if;
  select organization_id into caller_org from public.profiles where id = caller;
  select * into target from public.profiles where id = p_user_id and deactivated_at is null;
  if target.id is null or (target.organization_id is distinct from caller_org and not public.is_platform_admin(caller)) then
    raise exception 'not_found';
  end if;
  return jsonb_build_object('linkedin_url', target.linkedin_url, 'linkedin_headline', target.linkedin_headline);
end;
$$;
revoke all on function public.peer_linkedin(uuid) from public, anon;
grant execute on function public.peer_linkedin(uuid) to authenticated;

alter table public.sessions
  add column if not exists meeting_url text,
  add column if not exists last_activity_at timestamptz not null default now();

update public.sessions set meeting_url = 'https://teams.microsoft.com/l/meetup-join/ment-demo-' || id
where status = 'scheduled' and meeting_url is null;

create table if not exists public.session_messages (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  kind text not null default 'message' check (kind in ('request', 'message', 'system', 'schedule')),
  body text not null check (char_length(trim(body)) between 1 and 6000),
  created_at timestamptz not null default now()
);

create index if not exists session_messages_thread
  on public.session_messages(session_id, created_at, id);
create unique index if not exists session_messages_one_request
  on public.session_messages(session_id) where kind = 'request';

alter table public.session_messages enable row level security;
revoke all on public.session_messages from public, anon, authenticated;
grant select on public.session_messages to authenticated;
grant all on public.session_messages to service_role;

drop policy if exists session_messages_participants on public.session_messages;
create policy session_messages_participants on public.session_messages
  for select to authenticated using (
    exists (
      select 1 from public.sessions s
      where s.id = session_id and auth.uid() in (s.mentor_id, s.mentee_id)
    )
  );

insert into public.session_messages(session_id, sender_id, kind, body, created_at)
select s.id, s.mentee_id, 'request', s.outbound_message, s.created_at
from public.sessions s
where nullif(trim(s.outbound_message), '') is not null
  and not exists (
    select 1 from public.session_messages m where m.session_id = s.id and m.kind = 'request'
  );

create or replace function public.touch_session_from_message()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.sessions set last_activity_at = new.created_at where id = new.session_id;
  return new;
end;
$$;
revoke all on function public.touch_session_from_message() from public, anon, authenticated;
drop trigger if exists touch_session_from_message on public.session_messages;
create trigger touch_session_from_message after insert on public.session_messages
for each row execute function public.touch_session_from_message();

create or replace function public.log_session_completion()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.status = 'completed' and old.status is distinct from 'completed' then
    insert into public.session_messages(session_id, sender_id, kind, body)
    values (new.id, auth.uid(), 'system', 'Session completed.');
  end if;
  return new;
end;
$$;
revoke all on function public.log_session_completion() from public, anon, authenticated;
drop trigger if exists log_session_completion on public.sessions;
create trigger log_session_completion after update of status on public.sessions
for each row execute function public.log_session_completion();

create or replace function public.is_currently_available_mentor(p_user_id uuid)
returns boolean language sql stable set search_path = public as $$
  select coalesce(
    not p.mentorship_paused
    and (p.mentorship_unavailable_until is null or p.mentorship_unavailable_until <= current_date)
    and not exists (
      select 1 from public.mentorship_unavailable_periods up
      where up.user_id = p.id and current_date between up.start_date and up.end_date
    )
    and (
      select count(*) from public.sessions s
      where s.mentor_id = p.id and s.status in ('scheduled', 'completed')
        and coalesce(s.scheduled_at, s.accepted_at, s.created_at) >= date_trunc('week', now())
        and coalesce(s.scheduled_at, s.accepted_at, s.created_at) < date_trunc('week', now()) + interval '1 week'
    ) < p.weekly_meeting_limit
    and (
      select count(*) from public.sessions s
      where s.mentor_id = p.id and s.status in ('scheduled', 'completed')
        and coalesce(s.scheduled_at, s.accepted_at, s.created_at) >= date_trunc('month', now())
        and coalesce(s.scheduled_at, s.accepted_at, s.created_at) < date_trunc('month', now()) + interval '1 month'
    ) < p.monthly_meeting_limit,
    false
  )
  from public.profiles p where p.id = p_user_id
$$;
grant execute on function public.is_currently_available_mentor(uuid) to authenticated;

create or replace function public.directory_browse(
  p_limit integer default 12, p_offset integer default 0, p_persona text default null,
  p_program text default null, p_cohort_year integer default null, p_location text default null,
  p_working_language text default null, p_query text default null
)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  viewer uuid := auth.uid(); viewer_org uuid; org_type text; inter_org boolean;
  query_text text; persona_filter text; result jsonb;
begin
  if viewer is null then raise exception 'auth_required'; end if;
  select organization_id into viewer_org from public.profiles where id = viewer;
  select coalesce(o.type, 'intra') into org_type from public.organizations o where o.id = viewer_org;
  inter_org := org_type = 'inter';
  query_text := nullif(trim(coalesce(p_query, '')), '');
  persona_filter := case when p_persona in ('student', 'alumnus') then p_persona else null end;

  with eligible as (
    select p.* from public.profiles p
    where p.organization_id = viewer_org and p.id <> viewer and p.admin_scope = 'none'
      and p.onboarding_complete and p.deactivated_at is null
      and public.is_currently_available_mentor(p.id)
  ), filtered as (
    select e.* from eligible e
    where (persona_filter is null or e.role = persona_filter)
      and (p_program is null or e.program = p_program)
      and (p_cohort_year is null or e.cohort_year = p_cohort_year)
      and (p_location is null or e.location = p_location)
      and (p_working_language is null or e.working_language = p_working_language)
      and (query_text is null or e.name ilike '%' || query_text || '%'
        or coalesce(e.job_title, '') ilike '%' || query_text || '%'
        or coalesce(e.program, '') ilike '%' || query_text || '%'
        or coalesce(e.department, '') ilike '%' || query_text || '%'
        or coalesce(e.bio, '') ilike '%' || query_text || '%'
        or exists (select 1 from public.skills s where s.user_id = e.id and s.type = 'can_teach' and s.skill ilike '%' || query_text || '%'))
  ), page as (
    select f.* from filtered f order by lower(f.name), f.id
    limit least(greatest(coalesce(p_limit, 12), 1), 50) offset greatest(coalesce(p_offset, 0), 0)
  ), people_json as (
    select jsonb_build_object(
      'id', pg.id, 'name', case when inter_org then public.redacted_name(pg.name) else pg.name end,
      'role', pg.role, 'department', pg.department, 'program', pg.program,
      'cohort_year', pg.cohort_year, 'job_title', case when inter_org then null else pg.job_title end,
      'current_role', case when inter_org then null else pg.job_title end,
      'location', case when inter_org then null else pg.location end,
      'working_language', pg.working_language, 'bio', pg.bio, 'mentorship_available', true,
      'skills', coalesce((select jsonb_agg(jsonb_build_object('skill', s.skill, 'type', s.type) order by lower(s.skill))
        from public.skills s where s.user_id = pg.id and s.type = 'can_teach'), '[]'::jsonb)
    ) as item from page pg
  ), facets as (
    select
      (select coalesce(jsonb_agg(v order by v), '[]'::jsonb) from (select distinct program v from eligible where coalesce(program, '') <> '') x) programs,
      (select coalesce(jsonb_agg(v order by v), '[]'::jsonb) from (select distinct location v from eligible where coalesce(location, '') <> '') x) locations,
      (select coalesce(jsonb_agg(v order by v), '[]'::jsonb) from (select distinct working_language v from eligible) x) languages,
      (select coalesce(jsonb_agg(v order by v desc), '[]'::jsonb) from (select distinct cohort_year v from eligible where cohort_year is not null) x) cohort_years
  )
  select jsonb_build_object(
    'total', (select count(*) from filtered)::int,
    'people', (select coalesce(jsonb_agg(item), '[]'::jsonb) from people_json),
    'facets', jsonb_build_object('programs', f.programs, 'locations', f.locations, 'languages', f.languages, 'cohortYears', f.cohort_years)
  ) into result from facets f;
  return result;
end;
$$;
grant execute on function public.directory_browse(integer, integer, text, text, integer, text, text, text) to authenticated;

create or replace function public.my_meeting_capacity()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  caller uuid := auth.uid(); weekly_limit integer; monthly_limit integer;
  weekly_booked integer; monthly_booked integer;
begin
  if caller is null then raise exception 'auth_required'; end if;
  select p.weekly_meeting_limit, p.monthly_meeting_limit into weekly_limit, monthly_limit
  from public.profiles p where p.id = caller;
  select count(*) into weekly_booked from public.sessions s
  where s.mentor_id = caller and s.status in ('scheduled', 'completed')
    and coalesce(s.scheduled_at, s.accepted_at, s.created_at) >= date_trunc('week', now())
    and coalesce(s.scheduled_at, s.accepted_at, s.created_at) < date_trunc('week', now()) + interval '1 week';
  select count(*) into monthly_booked from public.sessions s
  where s.mentor_id = caller and s.status in ('scheduled', 'completed')
    and coalesce(s.scheduled_at, s.accepted_at, s.created_at) >= date_trunc('month', now())
    and coalesce(s.scheduled_at, s.accepted_at, s.created_at) < date_trunc('month', now()) + interval '1 month';
  return jsonb_build_object(
    'weekly_limit', weekly_limit, 'monthly_limit', monthly_limit,
    'weekly_booked', weekly_booked, 'monthly_booked', monthly_booked,
    'available', weekly_booked < weekly_limit and monthly_booked < monthly_limit
  );
end;
$$;
revoke all on function public.my_meeting_capacity() from public, anon;
grant execute on function public.my_meeting_capacity() to authenticated;

create or replace function public.enforce_meeting_capacity()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  weekly_limit integer; monthly_limit integer; weekly_booked integer; monthly_booked integer;
  meeting_time timestamptz := coalesce(new.scheduled_at, now());
begin
  if new.status <> 'scheduled' then return new; end if;
  if tg_op = 'UPDATE' and old.status = new.status and old.scheduled_at is not distinct from new.scheduled_at then return new; end if;
  select p.weekly_meeting_limit, p.monthly_meeting_limit into weekly_limit, monthly_limit
  from public.profiles p where p.id = new.mentor_id for update;
  select count(*) into weekly_booked from public.sessions s
  where s.mentor_id = new.mentor_id and s.id <> new.id and s.status in ('scheduled', 'completed')
    and coalesce(s.scheduled_at, s.accepted_at, s.created_at) >= date_trunc('week', meeting_time)
    and coalesce(s.scheduled_at, s.accepted_at, s.created_at) < date_trunc('week', meeting_time) + interval '1 week';
  select count(*) into monthly_booked from public.sessions s
  where s.mentor_id = new.mentor_id and s.id <> new.id and s.status in ('scheduled', 'completed')
    and coalesce(s.scheduled_at, s.accepted_at, s.created_at) >= date_trunc('month', meeting_time)
    and coalesce(s.scheduled_at, s.accepted_at, s.created_at) < date_trunc('month', meeting_time) + interval '1 month';
  if weekly_booked >= weekly_limit then raise exception 'weekly_capacity_reached'; end if;
  if monthly_booked >= monthly_limit then raise exception 'monthly_capacity_reached'; end if;
  return new;
end;
$$;
revoke all on function public.enforce_meeting_capacity() from public, anon, authenticated;

create or replace function public.session_payload(p_session public.sessions, p_viewer uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'id', p_session.id, 'mentor_id', p_session.mentor_id, 'mentee_id', p_session.mentee_id,
    'connection_id', p_session.connection_id, 'title', p_session.title,
    'scheduled_at', p_session.scheduled_at, 'duration_minutes', p_session.duration_minutes,
    'status', p_session.status, 'pre_session_question', p_session.pre_session_question,
    'outbound_message', p_session.outbound_message, 'meeting_url', p_session.meeting_url,
    'follow_up_intent', p_session.follow_up_intent, 'accepted_at', p_session.accepted_at,
    'occurred_at', p_session.occurred_at, 'last_activity_at', p_session.last_activity_at,
    'reflection', case when p_session.mentee_id = p_viewer then p_session.reflection else '' end,
    'mentor_reflection', case when p_session.mentor_id = p_viewer then p_session.mentor_reflection else '' end,
    'mentee_rating', case when p_session.mentee_id = p_viewer then p_session.mentee_rating else null end,
    'mentor_rating', case when p_session.mentor_id = p_viewer then p_session.mentor_rating else null end,
    'mentee_completed_at', p_session.mentee_completed_at,
    'mentor_completed_at', p_session.mentor_completed_at,
    'mentee_acknowledged_at', p_session.mentee_acknowledged_at,
    'topics', p_session.topics, 'created_at', p_session.created_at
  );
$$;

create or replace function public.my_sessions()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare caller uuid := auth.uid();
begin
  if caller is null then raise exception 'auth_required'; end if;
  return coalesce((select jsonb_agg(public.session_payload(s, caller) order by s.last_activity_at desc)
    from public.sessions s where caller in (s.mentor_id, s.mentee_id)), '[]'::jsonb);
end;
$$;

create or replace function public.my_session_relationships()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare caller uuid := auth.uid();
begin
  if caller is null then raise exception 'auth_required'; end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'person_id', case when s.mentor_id = caller then s.mentee_id else s.mentor_id end,
      'session_id', s.id, 'status', s.status, 'updated_at', s.last_activity_at
    )) from (
      select distinct on (least(mentor_id, mentee_id), greatest(mentor_id, mentee_id)) *
      from public.sessions where caller in (mentor_id, mentee_id)
      order by least(mentor_id, mentee_id), greatest(mentor_id, mentee_id), last_activity_at desc
    ) s
  ), '[]'::jsonb);
end;
$$;
revoke all on function public.my_session_relationships() from public, anon;
grant execute on function public.my_session_relationships() to authenticated;

create or replace function public.my_session_messages(p_session_id bigint)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare caller uuid := auth.uid();
begin
  if not exists (select 1 from public.sessions s where s.id = p_session_id and caller in (s.mentor_id, s.mentee_id)) then
    raise exception 'not_found';
  end if;
  return coalesce((select jsonb_agg(jsonb_build_object(
    'id', m.id, 'session_id', m.session_id, 'sender_id', m.sender_id,
    'kind', m.kind, 'body', m.body, 'created_at', m.created_at
  ) order by m.created_at, m.id) from public.session_messages m where m.session_id = p_session_id), '[]'::jsonb);
end;
$$;
revoke all on function public.my_session_messages(bigint) from public, anon;
grant execute on function public.my_session_messages(bigint) to authenticated;

create or replace function public.send_session_message(p_session_id bigint, p_body text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare caller uuid := auth.uid(); result public.session_messages;
begin
  if char_length(trim(coalesce(p_body, ''))) not between 1 and 6000 then raise exception 'invalid_message'; end if;
  if not exists (select 1 from public.sessions s where s.id = p_session_id and caller in (s.mentor_id, s.mentee_id)) then
    raise exception 'not_found';
  end if;
  insert into public.session_messages(session_id, sender_id, kind, body)
  values (p_session_id, caller, 'message', trim(p_body)) returning * into result;
  return to_jsonb(result);
end;
$$;
revoke all on function public.send_session_message(bigint, text) from public, anon;
grant execute on function public.send_session_message(bigint, text) to authenticated;

create or replace function public.pm_set_outbound_message(p_session_id bigint, p_message text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare caller uuid := auth.uid(); session_row public.sessions;
begin
  if caller is null then raise exception 'auth_required'; end if;
  if char_length(trim(coalesce(p_message, ''))) not between 1 and 6000 then raise exception 'invalid_outbound_message'; end if;
  select * into session_row from public.sessions where id = p_session_id for update;
  if not found or session_row.mentee_id <> caller then raise exception 'not_allowed'; end if;
  update public.sessions set outbound_message = trim(p_message), last_activity_at = now() where id = p_session_id;
  insert into public.session_messages(session_id, sender_id, kind, body, created_at)
  values (p_session_id, caller, 'request', trim(p_message), session_row.created_at)
  on conflict do nothing;
  insert into public.audit_logs(actor_id, action, target_type, target_id)
  values (caller, 'session_outbound_message_set', 'session', p_session_id::text);
  return jsonb_build_object('id', p_session_id, 'saved', true);
end;
$$;
revoke all on function public.pm_set_outbound_message(bigint, text) from public, anon;
grant execute on function public.pm_set_outbound_message(bigint, text) to authenticated;

create or replace function public.accept_session(p_session_id bigint, p_scheduled_at timestamptz default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare caller uuid := auth.uid(); row public.sessions;
begin
  select * into row from public.sessions where id = p_session_id for update;
  if row.id is null then raise exception 'session_not_found'; end if;
  if row.mentor_id <> caller or row.status <> 'pending' then raise exception 'forbidden'; end if;
  update public.sessions set status = 'scheduled', scheduled_at = coalesce(p_scheduled_at, scheduled_at),
    meeting_url = coalesce(meeting_url, 'https://teams.microsoft.com/l/meetup-join/ment-demo-' || id),
    last_activity_at = now() where id = p_session_id returning * into row;
  insert into public.session_messages(session_id, sender_id, kind, body)
  values (p_session_id, caller, 'system', 'Request accepted.');
  return public.session_payload(row, caller);
end;
$$;

create or replace function public.reschedule_session(p_session_id bigint, p_scheduled_at timestamptz)
returns jsonb language plpgsql security definer set search_path = public as $$
declare caller uuid := auth.uid(); row public.sessions;
begin
  if p_scheduled_at is null or p_scheduled_at <= now() then raise exception 'invalid_schedule'; end if;
  select * into row from public.sessions where id = p_session_id for update;
  if row.id is null then raise exception 'session_not_found'; end if;
  if caller not in (row.mentor_id, row.mentee_id) or row.status <> 'scheduled' then raise exception 'forbidden'; end if;
  update public.sessions set scheduled_at = p_scheduled_at,
    meeting_url = coalesce(meeting_url, 'https://teams.microsoft.com/l/meetup-join/ment-demo-' || id),
    last_activity_at = now() where id = p_session_id returning * into row;
  insert into public.session_messages(session_id, sender_id, kind, body)
  values (p_session_id, caller, 'schedule', 'Meeting scheduled for ' || to_char(p_scheduled_at at time zone 'UTC', 'Mon DD, YYYY HH24:MI') || ' UTC.');
  return public.session_payload(row, caller);
end;
$$;

create or replace function public.cancel_session(p_session_id bigint, p_status text default 'cancelled')
returns jsonb language plpgsql security definer set search_path = public as $$
declare caller uuid := auth.uid(); row public.sessions;
begin
  if p_status not in ('declined', 'cancelled') then raise exception 'invalid_status'; end if;
  select * into row from public.sessions where id = p_session_id for update;
  if row.id is null then raise exception 'session_not_found'; end if;
  if caller not in (row.mentor_id, row.mentee_id) then raise exception 'forbidden'; end if;
  update public.sessions set status = p_status, last_activity_at = now() where id = p_session_id returning * into row;
  insert into public.session_messages(session_id, sender_id, kind, body)
  values (p_session_id, caller, 'system', case when p_status = 'declined' then 'Request declined.' else 'Meeting cancelled.' end);
  return public.session_payload(row, caller);
end;
$$;

revoke all on function public.accept_session(bigint, timestamptz), public.reschedule_session(bigint, timestamptz), public.cancel_session(bigint, text) from public, anon;
grant execute on function public.accept_session(bigint, timestamptz), public.reschedule_session(bigint, timestamptz), public.cancel_session(bigint, text) to authenticated;
